import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import apiService from "@/app/api/api";
import ClientWrapper from "@/utils/ClientWrapper";
import AuthProvider from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Mini E-Commerce",
  description: "Generated by create next app",
};

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value || null;

  let user = null;

  if (token) {
    try {
      const res = await apiService.get<{ data: any }>("/v1/user", {
        headers: { Authorization: `Bearer ${token}` },
      });
      user = res.data;
    } catch (err) {
      console.error("Failed to fetch user in SSR:", err);
      // Don't throw error, just continue without user data
    }
  }

  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} bg-white`}>
        <AuthProvider initialUser={user} initialToken={token}>
          <ClientWrapper>{children}</ClientWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
