import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ClientWrapper from "@/utils/ClientWrapper";

export const metadata: Metadata = {
  title: "Mini E-Commerce",
  description: "Generated by create next app",
};

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} bg-white`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
