import { ProductCardType } from "@/types/product-card";

export const productsData: ProductCardType[] = [
  {
    id: 1,  
    image: '/image/product/shoes-dummy.svg',
    title: 'Sepatu Putih Bagus dan Berkualitas',
    price: 'Rp 100.000',
    location: 'Jakarta Pusat',
    ratings: '5',
    sold: 'Terjual 10',
  },
  {
      id: 2,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 3,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 4,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 5,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 6,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 7,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 8,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 9,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 10,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 11,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 12,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 13,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 14,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 15,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 16,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 17,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
    {
      id: 18,  
      image: '/image/product/shoes-dummy.svg',
      title: 'Sepatu Putih Bagus dan Berkualitas',
      price: 'Rp 100.000',
      location: 'Jakarta Pusat',
      ratings: '5',
      sold: 'Terjual 10',
    },
];
